nginxle:
  image: niiknow/nginx-letsencrypt:1.0.0
  restart: always
  tty: true
  stdin_open: true
  volumes_from:
    - nginxle-datavolume
  ports:
    - "80:80"
    - "443:443"
  environment:
    EMAIL: "${EMAIL}"
    DOMAINS: "${DOMAINS}"
    AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
    AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
    AWS_DEFAULT_REGION: "${AWS_DEFAULT_REGION}"
  labels:
    io.rancher.sidekicks: nginxle-datavolume
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label: ${host_label}

nginxle-datavolume:
  net: none
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
  volumes:
    - /app
    - /backup
  entrypoint: /bin/true
  image: busybox
