elasticsearch-masters:
  image: brickinc/elasticsearch-conf:v0.5.1
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.sidekicks: elasticsearch-base-master,elasticsearch-datavolume-masters
  environment:
    PLUGINS: '${es_plugins}'
  volumes_from:
    - elasticsearch-datavolume-masters
elasticsearch-datavolume-masters:
  labels:
    elasticsearch.datanode.config.version: '1'
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
  environment:
    PLUGINS: '${es_plugins}'
  volumes:
    - /usr/share/elasticsearch/data
    - /usr/share/elasticsearch/config
    - /opt/rancher/bin
  entrypoint: /bin/true
  image: elasticsearch:2.4.4
elasticsearch-base-master:
  labels:
    elasticsearch.master.config.version: '1'
    io.rancher.container.hostname_override: container_name
  environment:
    PLUGINS: '${es_plugins}'
  image: elasticsearch:2.4.4
  net: "container:elasticsearch-masters"
  volumes_from:
    - elasticsearch-datavolume-masters
  entrypoint:
    - /opt/rancher/bin/run.sh


elasticsearch-datanodes:
  image: brickinc/elasticsearch-conf:v0.5.1
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.sidekicks: elasticsearch-base-datanode,elasticsearch-datavolume-datanode
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
  environment:
    PLUGINS: '${es_plugins}'
  links:
    - elasticsearch-masters:es-masters
  volumes_from:
    - elasticsearch-datavolume-datanode
elasticsearch-datavolume-datanode:
  labels:
    elasticsearch.datanode.config.version: '1'
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
  environment:
    PLUGINS: '${es_plugins}'
  volumes:
    - /usr/share/elasticsearch/data
    - /usr/share/elasticsearch/config
    - /opt/rancher/bin
  entrypoint: /bin/true
  image: elasticsearch:2.4.4
elasticsearch-base-datanode:
  labels:
    elasticsearch.datanode.config.version: '1'
    io.rancher.container.hostname_override: container_name
  environment:
    PLUGINS: '${es_plugins}'
  image: elasticsearch:2.4.4
  links:
    - elasticsearch-masters:es-masters
  entrypoint:
    - /opt/rancher/bin/run.sh
  volumes_from:
    - elasticsearch-datavolume-datanode
  net: "container:elasticsearch-datanodes"


elasticsearch-clients:
  image: brickinc/elasticsearch-conf:v0.5.1
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.sidekicks: elasticsearch-base-clients,elasticsearch-datavolume-clients
  environment:
    PLUGINS: '${es_plugins}'
  links:
    - elasticsearch-masters:es-masters
  volumes_from:
    - elasticsearch-datavolume-clients
elasticsearch-datavolume-clients:
  labels:
    elasticsearch.datanode.config.version: '1'
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
  environment:
    PLUGINS: '${es_plugins}'
  volumes:
    - /usr/share/elasticsearch/data
    - /usr/share/elasticsearch/config
    - /opt/rancher/bin
  entrypoint: /bin/true
  image: elasticsearch:2.4.4
elasticsearch-base-clients:
  labels:
    elasticsearch.client.config.version: '1'
    io.rancher.container.hostname_override: container_name
  environment:
    PLUGINS: '${es_plugins}'
  image: elasticsearch:2.4.4
  volumes_from:
    - elasticsearch-datavolume-clients
  net: "container:elasticsearch-clients"
  entrypoint:
    - /opt/rancher/bin/run.sh


kopf:
  image: brickinc/kopf:v0.5.1
  ports:
    - "${kopf_port}:80"
  environment:
    KOPF_SERVER_NAME: 'es.dev'
    KOPF_ES_SERVERS: 'es-clients:9200'
    KOPF_BASIC_AUTH_LOGIN: "${kopf_login}"
    KOPF_BASIC_AUTH_PASSWORD: "${kopf_pass}"
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label: ${kopf_host_label}
  links:
    - elasticsearch-clients:es-clients
