.catalog:
  name: "Elasticsearch"
  version: "2.4.2-rancher1"
  description: "Elasticsearch. You know, for search"
  questions:
    - variable: cluster_name
      description: "Unique name to assign to your Elasticsearch cluster."
      label: "Cluster Name"
      type: "string"
      required: true
      default: "es"
    - variable: "kopf_port"
      label: "Public Port"
      description: "Unique public port for kopf"
      type: "int"
      default: 80
      required: true
    - variable: "kopf_login"
      label: "kopf user name"
      description: "Secure KOPF with basic credentials"
      type: "string"
      default: "user"
      required: true
    - variable: "kopf_pass"
      label: "kopf password"
      description: "use crypt() here - http://aspirine.org/htpasswd_en.html"
      type: "string"
      default: "must be the encrypted value"
      required: true
    - variable: "kopf_host_label"
      description: "Hosts with label to deploy KOPF"
      label: "KOPF Host label:"
      required: true
      default: "labelname=value"
      type: "string"
elasticsearch-masters:
  metadata:
    elasticsearch:
      yml:
        cluster.name: "${cluster_name}"
        node.name: "$${HOSTNAME}"
        node.data: "false"
        node.master: "true"
        network.host: "_site_"
elasticsearch-datanodes:
  metadata:
    elasticsearch:
      yml:
        cluster.name: "${cluster_name}"
        node.name: "$${HOSTNAME}"
        node.data: "true"
        node.master: "false"
        http.enabled: "false"
        network.host: "_site_"
elasticsearch-clients:
  metadata:
    elasticsearch:
      yml:
       cluster.name: "${cluster_name}"
       node.name: "$${HOSTNAME}"
       node.data: "false"
       node.master: "false"
       network.host: "_site_"
