vestacp:
  image: niiknow/vestacp:0.5.0
  restart: always
  tty: true
  stdin_open: true
  volumes_from:
    - vestacp-datavolume
  ports:
    - "2222:22"
    - "80:80"
    - "443:443"
    - "3306:3306"
    - "5432:5432"
    - "8083:8083"
  labels:
    io.rancher.sidekicks: vestacp-datavolume
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label: ${host_label}

vestacp-datavolume:
  net: none
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
  volumes:
    - /vesta
    - /home
    - /backup
  entrypoint: /bin/true
  image: busybox
