vestacp:
  image: brickinc/vestacp
  restart: always
  tty: true
  stdin_open: true
  volumes_from:
    - vestacp-datavolume
  labels:
    io.rancher.sidekicks: vestacp-datavolume
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label: ${host_label}

vestacp-datavolume:
  net: none
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
  volumes:
    - /vesta
  entrypoint: /bin/true
  image: busybox
