vestacp:
  image: brickinc/vestacp:0.3.1
  restart: always
  tty: true
  stdin_open: true
  volumes_from:
    - vestacp-datavolume
  ports:
    - "2222:22"
    - "8083:8083"
    - "5432:5432"
    - "3306:3306"
    - "443:443"
    - "25:25"
    - "993:993"
    - "110:110"
    - "53:53"
    - "54:54"
    - "80:80"
  labels:
    io.rancher.sidekicks: vestacp-datavolume
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label: ${host_label}

vestacp-datavolume:
  net: none
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
  volumes:
    - /vesta
    - /home
  entrypoint: /bin/true
  image: busybox
