vestacp:
  image: niiknow/vestacp:0.9.2
  cap_add: ['NET_RAW', 'NET_ADMIN']
  volumes_from:
    - vestacp-datavolume
  ports:
    - "2222:22"
    - "80:80"
    - "443:443"
    - "8083:8083"
  labels:
    io.rancher.container.pull_image: always
    io.rancher.sidekicks: vestacp-datavolume
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label: ${host_label}

vestacp-datavolume:
  image: busybox
  entrypoint: /bin/true
  net: none
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
  volumes:
    - /vesta
    - /home
    - /backup
