jenkins-primary:
  image: "brickinc/docker-jenkins-awscli"
  ports:
    - "8080:8080"
  labels:
    io.rancher.sidekicks: jenkins-plugins,jenkins-datavolume
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label: ${host_label}
  volumes_from:
    - jenkins-plugins
    - jenkins-datavolume
  entrypoint: /usr/share/jenkins/rancher/jenkins.sh
jenkins-plugins:
  image: rancher/jenkins-plugins:v0.1.1
jenkins-datavolume:
  image: "brickinc/docker-jenkins-awscli"
  labels:
    io.rancher.container.start_once: true
  entrypoint: /bin/true