.catalog:
  name: Jenkins
  version: 1.642.1-brick0
  description: |
    Jenkins CI management server with AWS CLI.
  questions:
    - variable: "plugins"
      type: "multiline"
      label: "List of Plugins"
      description: |
        List of plugins in the format <plugin_name>[:<version>]
        one entry per line.
      default: |
        credentials
        greenballs
        git
        junit
        git-client
        github-api
        github-oauth
        github
        plain-credentials
        scm-api
        ssh-credentials
        ssh-slaves
        swarm
        assembla-auth
        assembla
        discard-old-build 
        external-monitor-job 
        ghprb
        jackson2-api 
        jobConfigHistory
        oauth-credentials 
        workflow-aggregator

    - variable: "host_label"
      description: "Hosts with label to deploy jenkins"
      label: "Host label:"
      required: true
      default: "dock=6"
      type: "string"

jenkins-primary:
  metadata:
    plugins: |
      ${plugins}
