prerender:
  image: niiknow/prerender-redis:1.0.3
  labels:
    # Make prerender a global service
    io.rancher.scheduler.global: 'true'
  links:
    - redis:redis
  restart: always
  environment:
    REDIS_URL: "${REDIS_URL}"
    PAGE_TTL: ${PAGE_TTL}
    BASIC_AUTH_USERNAME: "${BASIC_AUTH_USERNAME}"
    BASIC_AUTH_PASSWORD: "${BASIC_AUTH_PASSWORD}"
    PRERENDER_NUM_WORKERS: ${PRERENDER_NUM_WORKERS}

redis:
  image: niiknow/redis:0.0.4
  restart: always
  labels:
    io.rancher.container.hostname_override: container_name
