prerender:
  image: niiknow/prerender-redis:1.0.1
  labels:
    # Make prerender a global service
    io.rancher.scheduler.global: 'true'
  links:
    - redis:redis
  restart: always
  tty: true
  stdin_open: true
  ports:
    - "4002:3000"
  environment:
    REDIS_URL: "${REDIS_URL}"
    PAGE_TTL: ${PAGE_TTL}
    BASIC_AUTH_USERNAME: "${BASIC_AUTH_USERNAME}"
    BASIC_AUTH_PASSWORD: "${BASIC_AUTH_PASSWORD}"
    PRERENDER_NUM_WORKERS: ${PRERENDER_NUM_WORKERS}
  health_check:
    # Which port to perform the check against
    port: 3000
    # For TCP, request_line needs to be '' or not shown
    # TCP Example:
    # request_line: ''
    request_line: GET /healthcheck HTTP/1.0
    # Interval is measured in milliseconds
    interval: 2000
    initializing_timeout: 60000
    reinitializing_timeout: 60000
    unhealthy_threshold: 3
    # Strategy for what to do when unhealthy
    # In this service, no action will occur when a container is found unhealthy
    strategy: recreate
    healthy_threshold: 2
    # Response timeout is measured in milliseconds
    response_timeout: 2000

redis:
  image: redis:3.2.9-alpine
  restart: always
  tty: true
  stdin_open: true
  labels:
    io.rancher.container.hostname_override: container_name
  health_check:
    port: 6379
    request_line: ''
    interval: 2000
    initializing_timeout: 60000
    reinitializing_timeout: 60000
    unhealthy_threshold: 3
    strategy: recreate
    healthy_threshold: 2
    response_timeout: 2000