lb-prerender:
  image: rancher/load-balancer-service
  ports:
    - 4001:3000
  links:
    - prerender:prerender
  labels:
    # Put load balancer containers on hosts with label
    io.rancher.scheduler.affinity:host_label: ${LB_HOST}

prerender:
  image: brickinc/digitalstore-seo:1.0.4
  labels:
    # Make prerender a global service
    io.rancher.scheduler.global: 'true'
  restart: always
  environment:
    ES_URL: "${ES_URL}"
    BASIC_AUTH_USERNAME: "${BASIC_AUTH_USERNAME}"
    BASIC_AUTH_PASSWORD: "${BASIC_AUTH_PASSWORD}"
    PRERENDER_NUM_WORKERS: ${PRERENDER_NUM_WORKERS}
