.catalog:
  name: "prerender"
  version: "v0.1"
  description: "prerender.io spa application"
  questions:    
    - variable: "LB_HOST"
      description: "load balancer host"
      label: "LB_HOST"
      default: "host=2"
      type: "string"
      required: true
    - variable: "ES_URL"
      description: "Elasticsearch URL"
      label: "ES_URL"
      default: "http://elasticsearch-clients.elasticsearch-2-prd.rancher.internal:9200"
      type: "string"
      required: true
    - variable: "BASIC_AUTH_USERNAME"
      description: "Allow for basic auth."
      label: "BASIC_AUTH_USERNAME"
      default: ""
      type: "string"
      required: false
    - variable: "BASIC_AUTH_PASSWORD"
      description: "Password for basic auth."
      label: "BASIC_AUTH_PASSWORD"
      default: ""
      type: "string"
      required: false
    - variable: "PRERENDER_NUM_WORKERS"
      description: "Number of workers"
      label: "PRERENDER_NUM_WORKERS"
      default: 4
      type: "int"
      required: false

prerender:
  health_check:
    # Which port to perform the check against
    port: 3000
    # For TCP, request_line needs to be '' or not shown
    # TCP Example:
    # request_line: ''
    request_line: GET /healthcheck HTTP/1.0
    # Interval is measured in milliseconds
    interval: 6000
    initializing_timeout: 60000
    reinitializing_timeout: 60000
    unhealthy_threshold: 3
    # Strategy for what to do when unhealthy
    # In this service, no action will occur when a container is found unhealthy
    strategy: recreate
    healthy_threshold: 2
    # Response timeout is measured in milliseconds
    response_timeout: 6000
