kong:
  image: mashape/kong
  links:
    - cassandra:cassandra
  ports:
    - 8000:8000
    - 8443:8443
  restart: always
  labels:
    io.rancher.container.hostname_override: container_name

cassandra:
  image: mashape/cassandra
  restart: always
  labels:
    io.rancher.container.hostname_override: container_name
