mongo:
  image: mongo
  restart: always
  tty: true
  stdin_open: true
  volumes_from:
    - mongo-datavolume
  labels:
    io.rancher.sidekicks: mongo-datavolume
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label: ${host_label}

mongo-datavolume:
  net: none
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
  volumes:
    - /data/db
  entrypoint: /bin/true
  image: busybox
